/**
 * DEVELOPMENT WEBPACK CONFIGURATION
 */

const path = require('path');
const webpack = require('webpack');
const autoprefixer = require('autoprefixer');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CircularDependencyPlugin = require('circular-dependency-plugin');

process.noDeprecation = true;

module.exports = (options) => ({
      devtool: 'cheap-module-eval-source-map',
      performance: {
        hints: false
      },
      entry: [
        'eventsource-polyfill', // Necessary for hot reloading with IE
        'webpack-hot-middleware/client?reload=true',
        path.join(process.cwd(), 'src/index.js') // Start with src/index.js
      ],
      mode: 'development',
      output: {
        //path: path.resolve(__dirname, 'dist'),
        path: path.resolve(process.cwd(), 'build'),
        filename: 'bundle.js',
        chunkFilename: '[name].chunk.js',
        //publicPath: ''
        publicPath: '/'
      },
      resolve: {
        extensions: ['.js', '.jsx']
      },
      module: {
        rules: [{
            test: /\.js$/,
            exclude: /node_modules/,
            use: {
              loader: 'babel-loader',
              options: options.babelQuery
            }
          },
          {
            test: /\.css$/,
            exclude: /node_modules/,
            use: [{
                loader: 'style-loader'
              },
              {
                loader: 'css-loader',
                options: {
                  importLoaders: 1,
                  modules: true,
                  localIdentName: '[name]__[local]__[hash:base64:5]'
                }
              },
              {
                loader: 'postcss-loader',
                options: {
                  ident: 'postcss',
                  plugins: () => [
                    autoprefixer({
                      browsers: [
                        "> 1%",
                        "last 2 versions"
                      ]
                    })
                  ]
                }
              }
            ]
          },
          {
            test: /\.(png|jpe?g|gif)$/,
            loader: 'url-loader?limit=8000&name=images/[name].[ext]'
          },
          {
            test: /\.html$/,
            use: 'html-loader'
          }
        ]
      },
      optimization: {
        namedModules: true, // NamedModulesPlugin()
        splitChunks: { // CommonsChunkPlugin()
          name: 'vendor',
          minChunks: 2
        },
        noEmitOnErrors: true, // NoEmitOnErrorsPlugin
        concatenateModules: true //ModuleConcatenationPlugin
      }
      // Add development plugins
      plugins: [
        new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
        new HtmlWebpackPlugin({
          filename: 'index.html',
          inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
          template: __dirname + '/src/index.html',
        }),
        new CircularDependencyPlugin({
          exclude: /a\.js|node_modules/, // exclude node_modules
          failOnError: false // show a warning when there is a circular dependency
        })
      ],
    };
